- type: jobIcon
  parent: SCPJobIcon
  id: SCPJobIconContainmentEngineer
  icon:
    sprite: /Textures/_SCP/Interface/job_icons.rsi
    state: maint

- type: jobIcon
  parent: SCPJobIcon
  id: SCPJobIconChiefContainmentEngineer
  icon:
    sprite: /Textures/_SCP/Interface/job_icons.rsi
    state: ce


- type: jobIcon
  parent: SCPJobIcon
  id: SCPJobIconCustodian
  icon:
    sprite: /Textures/_SCP/Interface/job_icons.rsi
    state: custodian