- type: department
  parent: SCPDepartmentBase
  id: SCPAdminDept
  name: department-SCPAdmin
  description: scp-department-admin-description
  color: "#334E6D"
  roles:
  - SCPSiteDirector
  primary: false