- type: job
  parent: SCPJobBase
  id: SCPChiefContainmentEngineer
  name: scp-job-name-chief-containment-engineer
  description: scp-job-description-chief-containment-engineer
  playTimeTracker: SCPJobChiefContainmentEngineer
#  requirements:
#  - !type:TotalJobsTimeRequirement
#    group: SCPMaintenance
#    time: 36000 # 10 hours
#  - !type:DepartmentTimeRequirement
#    department: SCPSecurity
#    time: 36000 # 10 hours
#  - !type:TotalJobsTimeRequirement
#    group: SCPJobsMedical
#    time: 36000 # 10 hours
#  - !type:DepartmentTimeRequirement
#    department: SCPCommand
#    time: 36000 # 10 hours
  weight: 10
  startingGear: SCPGearChiefContainmentEngineer
  icon: "SCPJobIconChiefContainmentEngineer"
  joinNotifyCrew: true
  supervisors: scp-job-supervisors-sd
  accessGroups:
  - Engineering

- type: startingGear
  id: SCPGearChiefContainmentEngineer
  equipment:
    jumpsuit: SCPClothingUniformEngineeringDirectorJumpsuit
    back: ClothingBackpackFilled
    shoes: SCPClothingShoesBootsDutySec
    id: SCPIDCardAdminLvl4
    ears: ClothingHeadsetEngineering
    eyes: ClothingEyesGlassesMeson
    belt: ClothingBeltChiefEngineerFilled
    head: ClothingHeadHatHardhatWhite

- type: entity
  parent: SCPSpawnPointJobBase
  id: SCPSpawnPointChiefContainmentEngineer
  name: chief containment engineer spawn point
  components:
  - type: SpawnPoint
    job_id: SCPChiefContainmentEngineer
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: cce

- type: playTimeTracker
  id: SCPJobChiefContainmentEngineer