- type: job
  parent: SCPJobBase
  id: SCPCustodian
  name: scp-job-name-custodian
  description: scp-job-description-custodian
  playTimeTracker: SCPJobCustodian
#  requirements:
#  - !type:TotalJobsTimeRequirement
#    group: SCPMaintenance
#    time: 36000 # 10 hours
#  - !type:DepartmentTimeRequirement
#    department: SCPSecurity
#    time: 36000 # 10 hours
#  - !type:TotalJobsTimeRequirement
#    group: SCPJobsMedical
#    time: 36000 # 10 hours
#  - !type:DepartmentTimeRequirement
#    department: SCPCommand
#    time: 36000 # 10 hours
  weight: 10
  startingGear: SCPGearCustodian
  icon: "SCPJobIconCustodian"
  joinNotifyCrew: true
  supervisors: scp-job-supervisors-cce
  accessGroups:
  - Engineering

- type: startingGear
  id: SCPGearCustodian
  equipment:
    jumpsuit: SCPClothingUniformSCPMaintenance
    back: ClothingBackpackFilled
    shoes: ClothingShoesGaloshes
    id: SCPIDCardAdminLvl2
    belt: ClothingBeltUtilityEngineering
    ears: ClothingHeadsetEngineering

- type: entity
  parent: SCPSpawnPointJobBase
  id: SCPSpawnPointCustodian
  name: containment engineer spawn point
  components:
  - type: SpawnPoint
    job_id: SCPCustodian
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: ce

- type: playTimeTracker
  id: SCPJobCustodian