- type: job
- type: job
  parent: SCPJobBase
  id: SCPLogistician
  name: scp-job-name-logistician
  description: scp-job-description-logistician
  playTimeTracker: SCPJobLogistician
#  requirements:
#  - !type:TotalJobsTimeRequirement
#    group: SCPMaintenance
#    time: 36000 # 10 hours
#  - !type:DepartmentTimeRequirement
#    department: SCPSecurity
#    time: 36000 # 10 hours
#  - !type:TotalJobsTimeRequirement
#    group: SCPJobsMedical
#    time: 36000 # 10 hours
#  - !type:DepartmentTimeRequirement
#    department: SCPCommand
#    time: 36000 # 10 hours
  weight: 10
  startingGear: SCPGearLogistician
  icon: "SCPJobIconLogistician"
  joinNotifyCrew: true
  supervisors: scp-job-supervisors-sd
  accessGroups:
  - Cargo

- type: startingGear
  id: SCPGearLogistician
  equipment:
    jumpsuit: SCPClothingUniformLogistics
    back: ClothingBackpackFilled
    shoes: SCPClothingShoesBootsDutySec
    id: SCPIDCardAdminLvl2
    ears: ClothingHeadsetCargo
    belt: BoxFolderClipboard

- type: entity
  parent: SCPSpawnPointJobBase
  id: SCPSpawnPointLogistician
  name: logistician spawn point
  components:
  - type: SpawnPoint
    job_id: SCPLogistician
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: logistics

- type: playTimeTracker
  id: SCPJobLogistician